//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.openoces.ooapi.pidservice.impl {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PIDRequest", Namespace="java:dk.certifikat.pid.webservices")]
    [System.SerializableAttribute()]
    public partial class PIDRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CPRField;
        
        private string PIDField;
        
        private string b64CertField;
        
        private string idField;
        
        private string serviceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CPR {
            get {
                return this.CPRField;
            }
            set {
                if ((object.ReferenceEquals(this.CPRField, value) != true)) {
                    this.CPRField = value;
                    this.RaisePropertyChanged("CPR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PID {
            get {
                return this.PIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PIDField, value) != true)) {
                    this.PIDField = value;
                    this.RaisePropertyChanged("PID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string b64Cert {
            get {
                return this.b64CertField;
            }
            set {
                if ((object.ReferenceEquals(this.b64CertField, value) != true)) {
                    this.b64CertField = value;
                    this.RaisePropertyChanged("b64Cert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceIdField, value) != true)) {
                    this.serviceIdField = value;
                    this.RaisePropertyChanged("serviceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PIDReply", Namespace="java:dk.certifikat.pid.webservices")]
    [System.SerializableAttribute()]
    public partial class PIDReply : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CPRField;
        
        private string PIDField;
        
        private string idField;
        
        private string redirURLField;
        
        private string statusCodeField;
        
        private string statusTextDKField;
        
        private string statusTextUKField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CPR {
            get {
                return this.CPRField;
            }
            set {
                if ((object.ReferenceEquals(this.CPRField, value) != true)) {
                    this.CPRField = value;
                    this.RaisePropertyChanged("CPR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PID {
            get {
                return this.PIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PIDField, value) != true)) {
                    this.PIDField = value;
                    this.RaisePropertyChanged("PID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string redirURL {
            get {
                return this.redirURLField;
            }
            set {
                if ((object.ReferenceEquals(this.redirURLField, value) != true)) {
                    this.redirURLField = value;
                    this.RaisePropertyChanged("redirURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.statusCodeField, value) != true)) {
                    this.statusCodeField = value;
                    this.RaisePropertyChanged("statusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string statusTextDK {
            get {
                return this.statusTextDKField;
            }
            set {
                if ((object.ReferenceEquals(this.statusTextDKField, value) != true)) {
                    this.statusTextDKField = value;
                    this.RaisePropertyChanged("statusTextDK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string statusTextUK {
            get {
                return this.statusTextUKField;
            }
            set {
                if ((object.ReferenceEquals(this.statusTextUKField, value) != true)) {
                    this.statusTextUKField = value;
                    this.RaisePropertyChanged("statusTextUK");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ooapi.pidservice.impl.pidwsdocPort")]
    public interface pidwsdocPort {
        
        // CODEGEN: Generating message contract since element name pIDRequests from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        org.openoces.ooapi.pidservice.impl.pidResponse pid(org.openoces.ooapi.pidservice.impl.pidRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        int testConnection(int intVal);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        void test();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pidRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pid", Namespace="http://localhost/", Order=0)]
        public org.openoces.ooapi.pidservice.impl.pidRequest1Body Body;
        
        public pidRequest1() {
        }
        
        public pidRequest1(org.openoces.ooapi.pidservice.impl.pidRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class pidRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public org.openoces.ooapi.pidservice.impl.PIDRequest[] pIDRequests;
        
        public pidRequest1Body() {
        }
        
        public pidRequest1Body(org.openoces.ooapi.pidservice.impl.PIDRequest[] pIDRequests) {
            this.pIDRequests = pIDRequests;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pidResponse", Namespace="http://localhost/", Order=0)]
        public org.openoces.ooapi.pidservice.impl.pidResponseBody Body;
        
        public pidResponse() {
        }
        
        public pidResponse(org.openoces.ooapi.pidservice.impl.pidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class pidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public org.openoces.ooapi.pidservice.impl.PIDReply[] result;
        
        public pidResponseBody() {
        }
        
        public pidResponseBody(org.openoces.ooapi.pidservice.impl.PIDReply[] result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface pidwsdocPortChannel : org.openoces.ooapi.pidservice.impl.pidwsdocPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pidwsdocPortClient : System.ServiceModel.ClientBase<org.openoces.ooapi.pidservice.impl.pidwsdocPort>, org.openoces.ooapi.pidservice.impl.pidwsdocPort {
        
        public pidwsdocPortClient() {
        }
        
        public pidwsdocPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public pidwsdocPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pidwsdocPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pidwsdocPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.openoces.ooapi.pidservice.impl.pidResponse org.openoces.ooapi.pidservice.impl.pidwsdocPort.pid(org.openoces.ooapi.pidservice.impl.pidRequest1 request) {
            return base.Channel.pid(request);
        }
        
        public org.openoces.ooapi.pidservice.impl.PIDReply[] pid(org.openoces.ooapi.pidservice.impl.PIDRequest[] pIDRequests) {
            org.openoces.ooapi.pidservice.impl.pidRequest1 inValue = new org.openoces.ooapi.pidservice.impl.pidRequest1();
            inValue.Body = new org.openoces.ooapi.pidservice.impl.pidRequest1Body();
            inValue.Body.pIDRequests = pIDRequests;
            org.openoces.ooapi.pidservice.impl.pidResponse retVal = ((org.openoces.ooapi.pidservice.impl.pidwsdocPort)(this)).pid(inValue);
            return retVal.Body.result;
        }
        
        public int testConnection(int intVal) {
            return base.Channel.testConnection(intVal);
        }
        
        public void test() {
            base.Channel.test();
        }
    }
}
